from enum import Enum


class ConsumeResult(Enum):
    INVALID = 0
    PREFIX = 1
    COMPLETE = 2


class DecoderState(Enum):
    START = 0

    EXPECT_OPEN_BRACE = 1

    EXPECT_NAME_KEY = 2
    EXPECT_NAME_COLON = 3
    EXPECT_FUNCTION_NAME = 4

    EXPECT_COMMA = 5

    EXPECT_PARAMETERS_KEY = 6
    EXPECT_PARAMETERS_COLON = 7
    EXPECT_PARAMETERS_OPEN = 8

    EXPECT_PARAMETER_NAME = 9
    EXPECT_PARAMETER_COLON = 10
    EXPECT_PARAMETER_VALUE = 11

    EXPECT_PARAMETER_SEPARATOR = 12

    EXPECT_CLOSE_PARAMETERS = 13
    EXPECT_CLOSE_OBJECT = 14

    FINISHED = 15